### ISSUE TITLE
Error: Call to a member function getNames() on null

### ISSUE THREAD

**Issue by kelunik** [amphp/aerys#133]
**Steps to reproduce**

1. Modify `demo.php` and add the following route:

```
    ->post("/body3", function(Request $req, Response $res) {
        $body = yield Aerys\parseBody($req);
        var_dump($body);
    })
```

2. Create `request.txt`:

```
POST /body3 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 65004
Content-Type: application/x-www-form-urlencoded; charset=utf-8
Host: localhost:1337
User-Agent: HTTPie/0.9.2

```

3. Send request to Aerys: `cat request.txt | telnet localhost 1337`

**Result**

```
[2017-02-24 12:21:25] debug POST /body3 HTTP/1.1 @ 127.0.0.1:33868
[2017-02-24 12:21:25] critical Error: Call to a member function getNames() on null in /home/kelunik/GitHub/amphp/aerys/lib/BodyParser.php:72
Stack trace:
#0 /home/kelunik/GitHub/amphp/aerys/vendor/amphp/amp/lib/NativeReactor.php(100): Aerys\BodyParser->Aerys\{closure}('0000000014e4d86...', NULL)
#1 /home/kelunik/GitHub/amphp/aerys/vendor/amphp/amp/lib/NativeReactor.php(172): Amp\NativeReactor->tryImmediate(Object(stdClass))
#2 /home/kelunik/GitHub/amphp/aerys/vendor/amphp/amp/lib/NativeReactor.php(71): Amp\NativeReactor->doTick(false)
#3 /home/kelunik/GitHub/amphp/aerys/vendor/amphp/amp/lib/functions.php(46): Amp\NativeReactor->run(Object(Closure))
#4 /home/kelunik/GitHub/amphp/aerys/bin/aerys(106): Amp\run(Object(Closure))
#5 {main}
```

**Expected Result**

No exception.

**Comment by kelunik** [comment]
@bwoebi Is this one fixed by https://github.com/amphp/aerys/commit/7ddb3770f8fc6f301fe7698de2575af2e49bb80b?

**Comment by bwoebi** [comment]
Yes, it should.

**Comment by joshdifabio** [comment]
Would it be worth creating regression tests when bugs are reported?

**Comment by bwoebi** [comment]
Yep. Just not having much time the next three days...

**Comment by kelunik** [comment]
Yes, this one is fixed.
