### ISSUE TITLE
Bug: LogicException when ending responses

### ISSUE THREAD

**Issue by marcioAlmada** [amphp/aerys#146]
It seems weird that a bug like this could exist since it affects the request/response cycle too much or perhaps I'm doing something wrong. Minimum steps to reproduce:

```php
# index.php
<?php

(new Aerys\Host)
    ->use(function($request, $response){
        $body = '';
        $bodyParser = $request->getBody();
        while (yield $bodyParser->valid()) $body .= $bodyParser->consume();

        $response->end($body);
    })
    ->expose("*", 3000);
;
```

Running:
```
php -d zend.assertions=1 ./vendor/bin/aerys -d -c index.php
```

Request:
```
curl -X POST \
  http://localhost/blah \
  -H 'content-type: application/json' \
  -d '{
  "param": "whathevs"
}
'
```
Exception:
```
LogicException: Promise already resolved in [...]/vendor/amphp/amp/lib/Placeholder.php:70
Stack trace:
#0 [...]/vendor/amphp/amp/lib/PrivatePromisor.php(20): Amp\PrivatePlaceholder->resolve(Object(Aerys\ClientException), NULL)
#1 [...]/vendor/amphp/amp/lib/PrivatePromisor.php(72): Amp\PrivatePlaceholder->Amp\{closure}(Object(Aerys\ClientException), NULL)
#2 [...]/vendor/amphp/aerys/lib/Server.php(905): Amp\Deferred->fail(Object(Aerys\ClientException))
#3 [...]/vendor/amphp/aerys/lib/Server.php(430): Aerys\Server->close(Object(Aerys\Client))
#4 [...]/vendor/amphp/aerys/lib/Server.php(422): Aerys\Server->onResponseDataDone(Object(Aerys\Client))
#5 [...]/vendor/amphp/aerys/lib/Http1Driver.php(156): Aerys\Server->writeResponse(Object(Aerys\Client), true)
#6 [internal function]: Aerys\Http1Driver->writer(Object(Aerys\InternalRequest))
#7 [...]/vendor/amphp/aerys/lib/functions.php(389): Generator->send(NULL)
#8 [internal function]: Aerys\responseCodec(Object(Generator), Object(Aerys\InternalRequest))
#9 [...]/vendor/amphp/aerys/lib/StandardResponse.php(238): Generator->send(NULL)
#10 /home/marcioalmada/P/blacklist-php/bug.php(9): Aerys\StandardResponse->end('{\n  "param": "whathevs...')
#11 [internal function]: Aerys\Bootstrapper->{closure}(Object(Aerys\StandardRequest), Object(Aerys\StandardResponse))
#12 [...]/vendor/amphp/amp/lib/functions.php(876): Generator->send(false)
#13 [...]/vendor/amphp/amp/lib/Placeholder.php(91): Amp\__coroutineSend(NULL, false, Object(Amp\CoroutineState))
#14 [...]/vendor/amphp/amp/lib/PrivatePromisor.php(20): Amp\PrivatePlaceholder->resolve(NULL, false)
#15 [...]/vendor/amphp/amp/lib/PrivatePromisor.php(57): Amp\PrivatePlaceholder->Amp\{closure}(NULL, false)
#16 [...]/vendor/amphp/amp/lib/PromiseStream.php(38): Amp\Deferred->succeed(false)
#17 [...]/vendor/amphp/amp/lib/Placeholder.php(91): Amp\PromiseStream->Amp\{closure}(NULL, NULL, NULL)
#18 [...]/vendor/amphp/amp/lib/PrivatePromisor.php(20): Amp\PrivatePlaceholder->resolve(NULL, NULL)
#19 [...]/vendor/amphp/amp/lib/PrivatePromisor.php(57): Amp\PrivatePlaceholder->Amp\{closure}(NULL, NULL)
#20 [...]/vendor/amphp/aerys/lib/Server.php(574): Amp\Deferred->succeed()
#21 [...]/vendor/amphp/aerys/lib/Server.php(539): Aerys\Server->onParsedMessageWithEntity(Object(Aerys\Client), Array)
#22 [...]/vendor/amphp/aerys/lib/Http1Driver.php(529): Aerys\Server->onParseEmit(Object(Aerys\Client), 5, Array, NULL)
#23 [internal function]: Aerys\Http1Driver->parser(Object(Aerys\Client))
#24 [...]/vendor/amphp/aerys/lib/Server.php(524): Generator->send('POST /blah')
#25 [...]/vendor/amphp/amp/lib/NativeReactor.php(265): Aerys\Server->onReadable('000000006ebb0fb...', Resource id #113, Object(Aerys\Client))
#26 [...]/vendor/amphp/amp/lib/NativeReactor.php(249): Amp\NativeReactor->doIoCallback('000000006ebb0fb...', Object(stdClass), Resource id #113)
#27 [...]/vendor/amphp/amp/lib/NativeReactor.php(214): Amp\NativeReactor->selectActionableStreams(0.7158)
#28 [...]/vendor/amphp/amp/lib/NativeReactor.php(71): Amp\NativeReactor->doTick(false)
#29 [...]/vendor/amphp/amp/lib/functions.php(46): Amp\NativeReactor->run(Object(Closure))
#30 [...]/vendor/amphp/aerys/bin/aerys(106): Amp\run(Object(Closure))
#31 {main}
```

**Comment by marcioAlmada** [comment]
Thanks!
