### ISSUE TITLE
Pipelined connection rise exception

### ISSUE THREAD

**Issue by torinaki** [amphp/aerys#147]
Seems if we are using pipelined request server do not handle it properly. Even it do not support pipelined requests it must not throw exception.

Server configuration:
```php
<?php

const AERYS_OPTIONS = [
    // help avoid connection errors during benchmark
    'connectionsPerIP' => 100,
    // to emulate NodeJS behavior
    'keepAliveTimeout' => 10000,
    'maxKeepAliveRequests' => 10000,
];

(new \Aerys\Host)
    ->name("localhost")
    ->expose("0.0.0.0", 8080)
    ->use(function(Aerys\Request $req, Aerys\Response $resp) {
        $data = 'Hello world!';
        $status = 200;
        $resp->addHeader('Content-Type', 'text/plain; charset=utf-8');
        $resp->addHeader('X-Powered-By', 'AerysServer');
        $resp->setStatus($status);
        $resp->end($data);
    });
```

Lua pipelined script:
```lua
init = function(args)
    local r = {}
    for i = 1, 20 do
        r[i] = wrk.format(nil, "/?" .. i)
    end


    req = table.concat(r)
end

request = function()
    return req
end
```

```bash
wrk -t1 -c100 -d1s --latency -s pipeline.lua http://127.0.0.1:8080/
```

Get following exception after benchmark is finished:
```text
[2017-05-13 00:32:51] critical LogicException: Promise already resolved in /app/aerys/vendor/amphp/amp/lib/Placeholder.php:70
Stack trace:
#0 /app/aerys/vendor/amphp/amp/lib/PublicPromisor.php(63): Amp\Deferred->resolve(Object(Aerys\ClientException), NULL)
#1 /app/aerys/vendor/amphp/aerys/lib/Server.php(913): Amp\Deferred->fail(Object(Aerys\ClientException))
#2 /app/aerys/vendor/amphp/aerys/lib/Server.php(506): Aerys\Server->close(Object(Aerys\Client))
#3 /app/aerys/vendor/amphp/amp/lib/NativeReactor.php(265): Aerys\Server->onReadable('00000000369e395...', Resource id #183, Object(Aerys\Client))
#4 /app/aerys/vendor/amphp/amp/lib/NativeReactor.php(249): Amp\NativeReactor->doIoCallback('00000000369e395...', Object(stdClass), Resource id #183)
#5 /app/aerys/vendor/amphp/amp/lib/NativeReactor.php(214): Amp\NativeReactor->selectActionableStreams(0.0975)
#6 /app/aerys/vendor/amphp/amp/lib/NativeReactor.php(71): Amp\NativeReactor->doTick(false)
#7 /app/aerys/vendor/amphp/amp/lib/functions.php(46): Amp\NativeReactor->run(Object(Closure))
#8 /app/aerys/vendor/amphp/aerys/bin/aerys-worker(56): Amp\run(Object(Closure))
#9 {main}
```

**Comment by bwoebi** [comment]
I'm not able to reproduce this with current master given your instructions.
Your lua script definitely works according to the debug log, but I get no such exception...

**Comment by torinaki** [comment]
@bwoebi, thanks you! Hmm... I will check with latest master

**Comment by torinaki** [comment]
I'm also didn't succeed on my Mac. It is only reproducible using my Docker image. It is reproducible under different PHP versions. I guess it might be related that I'm running everything inside docker under root user. I will check.

To reproduce run in console:

Get docker image:
```bash
docker pull dmitrybalabka/aerys-benchmark:php70
```
Run server:
```bash
docker run dmitrybalabka/aerys-benchmark:php70 php -n -c ./php/default-opcache.ini ./aerys/vendor/bin/aerys -w 1 -c ./aerys/server-wo-timeout.php --worker-args="-n"
```

In other console:

Get image id that is currently running:
```bash
docker ps
```
Run benchmark:
```bash
docker exec -it <image id>   ./bin/wrk -t1 -c100 -d1s --latency -s ./report/pipeline.lua http://127.0.0.1:8080/
```

After benchmark was finished you will see in first console exception.

**Comment by bwoebi** [comment]
Yay for system dependent bugs … I'll investigate, thanks.

**Comment by bwoebi** [comment]
Could reproduce it too in my Debian VM, thanks; looking now.
