### ISSUE TITLE
Demo page syntax error

### ISSUE THREAD

**Issue by sushi2k** [amphp/aerys#78]
Hi,

after cloning the repo, installing via composer and starting aerys according to the readme I get an error.

```
➜  aerys git:(master) ✗ php -d bin/aerys -c demo.php

PHP:  syntax error, unexpected '{' in /root/server/aerys/demo.php on line 3
```

The service is not starting, and also the port 1337 is not used by aerys. I do not find the syntax error to fix it as it looks valid to me.

**Comment by staabm** [comment]
Are you using php7?

**Comment by bwoebi** [comment]
Right, only possibility to get that error is to use a version older than PHP 7.0.0.

**Comment by staabm** [comment]
@bwoebi I guess we should hard exit with a proper error message when used php version is < 7

**Comment by bwoebi** [comment]
@sushi2k Also your command is wrong, should be `php bin/aerys -d -c demo.php`

@staabm doesn't help much, when the entry file is already only compliable with PHP 7...

**Comment by kelunik** [comment]
@bwoebi We can change the demo file and include the actual demo file then.

**Comment by sushi2k** [comment]
Thanks for all your comments, but I am using PHP 7. 

```
➜  aerys git:(master) ✗ php -v
PHP 7.0.3-3+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

I just did a git pull and this is now the output with the debug flag set correctly. 

```
➜  aerys git:(master) ✗ php bin/aerys -c -d demo.php
[00:38:58] warning Running aerys in debug mode with assertions disabled is not recommended; enable assertions in php.ini (zend.assertions = 1) or disable debug mode (-d) to hide this warning.
[00:38:58] info Using config file found at
[00:38:58] warning include(): Filename cannot be empty in /root/server/aerys/lib/Bootstrapper.php on line 26
[00:38:58] warning include(): Failed opening '' for inclusion (include_path='.:/usr/share/php:') in /root/server/aerys/lib/Bootstrapper.php on line 26
[00:38:58] critical DomainException: Config file inclusion failure:  in /root/server/aerys/lib/Bootstrapper.php:29
Stack trace:
#0 /root/server/aerys/lib/DebugProcess.php(32): Aerys\Bootstrapper->boot(Object(Aerys\ConsoleLogger), Object(Aerys\Console))
#1 /root/server/aerys/lib/Process.php(47): Aerys\DebugProcess->doStart(Object(Aerys\Console))
#2 [internal function]: Aerys\Process->start(Object(Aerys\Console))
#3 /root/server/aerys/vendor/amphp/amp/lib/functions.php(775): Generator->current()
#4 /root/server/aerys/vendor/amphp/amp/lib/functions.php(763): Amp\__coroutineAdvance(Object(Amp\CoroutineState))
#5 /root/server/aerys/bin/aerys(95): Amp\resolve(Object(Generator))
#6 [internal function]: {closure}('000000004a5998c...', NULL)
#7 /root/server/aerys/vendor/amphp/amp/lib/functions.php(775): Generator->current()
#8 /root/server/aerys/vendor/amphp/amp/lib/functions.php(763): Amp\__coroutineAdvance(Object(Amp\CoroutineState))
#9 /root/server/aerys/vendor/amphp/amp/lib/NativeReactor.php(101): Amp\resolve(Object(Generator))
#10 /root/server/aerys/vendor/amphp/amp/lib/NativeReactor.php(60): Amp\NativeReactor->tryImmediate(Object(stdClass))
#11 /root/server/aerys/vendor/amphp/amp/lib/functions.php(46): Amp\NativeReactor->run(Object(Closure))
#12 /root/server/aerys/bin/aerys(96): Amp\run(Object(Closure))
#13 {main}
```

**Comment by bwoebi** [comment]
`-c -d` ≠ `-d -c`

**Comment by sushi2k** [comment]
Now the server is running. Thanks for your help.
