### ISSUE TITLE
HTTP/2 in Aerys not working

### ISSUE THREAD

**Issue by sushi2k** [amphp/aerys#79]
Hi,
I just tried to make a HTTP/2 request to the demo page of aerys, but I get a StackTrace once the request is sent. 

See screenshot for details. 
![screenshot at feb 11 15-39-43](https://cloud.githubusercontent.com/assets/5951320/12971399/c63aa0e4-d0d5-11e5-8504-9b98d75b61f6.png)

This is the full error message:
```
[07:39:09] error Error: Class 'Aerys\Failure' not found in /root/fuzzing/server/aerys/lib/Http2Driver.php:275
Stack trace:
#0 [internal function]: Aerys\Http2Driver->writer(Object(Aerys\InternalRequest))
#1 /root/fuzzing/server/aerys/lib/functions.php(476): Generator->send(NULL)                                             [0/354]
#2 [internal function]: Aerys\responseCodec(Object(Generator), Object(Aerys\InternalRequest))
#3 /root/fuzzing/server/aerys/lib/StandardResponse.php(257): Generator->send(NULL)
#4 /root/fuzzing/server/aerys/lib/StandardResponse.php(162): Aerys\StandardResponse->end('<html><body><h1...')
#5 /root/fuzzing/server/aerys/demo.php(4) : eval()'d code(17): Aerys\StandardResponse->send('<html><body><h1...')
#6 /root/fuzzing/server/aerys/lib/Router.php(68): Aerys\Bootstrapper->{closure}(Object(Aerys\StandardRequest), Object(Aerys\Sta
ndardResponse), Array)
#7 /root/fuzzing/server/aerys/lib/Bootstrapper.php(179): Aerys\Router->__invoke(Object(Aerys\StandardRequest), Object(Aerys\Sta
ndardResponse))
#8 [internal function]: class@anonymous->__invoke(Object(Aerys\StandardRequest), Object(Aerys\StandardResponse))
#9 /root/fuzzing/server/aerys/vendor/amphp/amp/lib/functions.php(775): Generator->current()
#10 /root/fuzzing/server/aerys/vendor/amphp/amp/lib/functions.php(763): Amp\__coroutineAdvance(Object(Amp\CoroutineState))
#11 /root/fuzzing/server/aerys/lib/Server.php(749): Amp\resolve(Object(Generator))
#12 /root/fuzzing/server/aerys/lib/Server.php(701): Aerys\Server->tryApplication(Object(Aerys\InternalRequest), Object(class@an
onymous))
#13 /root/fuzzing/server/aerys/lib/Server.php(561): Aerys\Server->respond(Object(Aerys\InternalRequest))
#14 /root/fuzzing/server/aerys/lib/Server.php(539): Aerys\Server->onParsedMessageWithoutEntity(Object(Aerys\Client), Array)
#15 /root/fuzzing/server/aerys/lib/Http1Driver.php(302): Aerys\Server->onParseEmit(Array, Object(Aerys\Client))
#16 [internal function]: Aerys\Http1Driver->parser(Object(Aerys\Client))
#17 /root/fuzzing/server/aerys/lib/Server.php(532): Generator->send('GET / HTTP/1.1\r...')
#18 /root/fuzzing/server/aerys/vendor/amphp/amp/lib/NativeReactor.php(257): Aerys\Server->onReadable('000000005be04d7...', Reso
urce id #131, Object(Aerys\Client))
#19 /root/fuzzing/server/aerys/vendor/amphp/amp/lib/NativeReactor.php(244): Amp\NativeReactor->doIoCallback('000000005be04d7...
', Object(stdClass), Resource id #131)
#20 /root/fuzzing/server/aerys/vendor/amphp/amp/lib/NativeReactor.php(214): Amp\NativeReactor->selectActionableStreams(0.3786)
#21 /root/fuzzing/server/aerys/vendor/amphp/amp/lib/NativeReactor.php(70): Amp\NativeReactor->doTick(false)
#22 /root/fuzzing/server/aerys/vendor/amphp/amp/lib/functions.php(46): Amp\NativeReactor->run(Object(Closure))
#23 /root/fuzzing/server/aerys/bin/aerys(96): Amp\run(Object(Closure))
#24 {main}




```

**Comment by staabm** [comment]
closed by 7740b7f  could you re-try with latest master?

**Comment by bwoebi** [comment]
That's not the root cause though (there should be no Failure instantiated at all)

**Comment by bwoebi** [comment]
The issue was the RFC requiring "URL-safe" base64 … added a strtr, fine now.

**Comment by kelunik** [comment]
See comment on last commit.

**Comment by bwoebi** [comment]
@kelunik I see no comment on the latest commit?

**Comment by kelunik** [comment]
https://github.com/amphp/aerys/commit/52e51e10c46f1fd73141fb8a916da401c7e3c112#commitcomment-16029591

**Comment by sushi2k** [comment]
Thanks for quick fix. It's working now. 

![screenshot at feb 11 21-26-04](https://cloud.githubusercontent.com/assets/5951320/12977534/2d857294-d106-11e5-975d-116a82e7ab5e.png)

**Comment by kelunik** [comment]
Thanks for the report and confirmation. :+1:
