### ISSUE TITLE
Crash in debug mode

### ISSUE THREAD

**Issue by douggr** [amphp/aerys#99]
I'm getting this weird error if starting with 'debug' = true in my config file.

```shell
$ php vendor/bin/aerys -c config.php 
[14:17:02] warning Running aerys in production with assertions enabled is not recommended; disable assertions in php.ini (zend.assertions = -1) for best performance or enable debug mode (-d) to hide this warning.
[14:17:02] warning stream_socket_server(): unable to connect to tcp://0.0.0.0:1334 (Address already in use) in /.../megan/vendor/amphp/aerys/lib/Server.php on line 265
[14:17:02] critical RuntimeException: Failed binding socket on tcp://0.0.0.0:1334: [Err# 0] Address already in use in /.../megan/vendor/amphp/aerys/lib/Server.php:266
Stack trace:
#0 /.../megan/vendor/amphp/aerys/lib/Server.php(177): Aerys\Server->bind('tcp://0.0.0.0:1...', Resource id #92)
#1 [internal function]: Aerys\Server->doStart()
#2 /.../megan/vendor/amphp/amp/lib/functions.php(791): Generator->current()
#3 /.../megan/vendor/amphp/amp/lib/functions.php(779): Amp\__coroutineAdvance(Object(Amp\CoroutineState))
#4 /.../megan/vendor/amphp/aerys/lib/Server.php(157): Amp\resolve(Object(Generator))
#5 /.../megan/vendor/amphp/aerys/lib/WorkerProcess.php(36): Aerys\Server->start()
#6 /.../megan/vendor/amphp/aerys/lib/Process.php(48): Aerys\WorkerProcess->doStart(Object(Aerys\Console))
#7 /.../megan/vendor/amphp/aerys/bin/aerys-worker(53): Aerys\Process->start(Object(Aerys\Console))
#8 [internal function]: {closure}('000000000fa9234...', NULL)
#9 /.../megan/vendor/amphp/amp/lib/functions.php(791): Generator->current()
#10 /.../megan/vendor/amphp/amp/lib/functions.php(779): Amp\__coroutineAdvance(Object(Amp\CoroutineState))
#11 /.../megan/vendor/amphp/amp/lib/EvReactor.php(133): Amp\resolve(Object(Generator))
#12 /.../megan/vendor/amphp/amp/lib/EvReactor.php(92): Amp\EvReactor->tryImmediate(Object(stdClass))
#13 /.../megan/vendor/amphp/amp/lib/functions.php(46): Amp\EvReactor->run(Object(Closure))
#14 /.../megan/vendor/amphp/aerys/bin/aerys-worker(54): Amp\run(Object(Closure))
#15 {main}
[14:17:02] warning stream_socket_server(): unable to connect to tcp://0.0.0.0:1334 (Unknown error) in /.../megan/vendor/amphp/aerys/lib/Server.php on line 265
[14:17:02] critical RuntimeException: Failed binding socket on tcp://0.0.0.0:1334: [Err# 0]  in /.../megan/vendor/amphp/aerys/lib/Server.php:266
Stack trace:
#0 /.../megan/vendor/amphp/aerys/lib/Server.php(177): Aerys\Server->bind('tcp://0.0.0.0:1...', Resource id #92)
#1 [internal function]: Aerys\Server->doStart()
#2 /.../megan/vendor/amphp/amp/lib/functions.php(791): Generator->current()
#3 /.../megan/vendor/amphp/amp/lib/functions.php(779): Amp\__coroutineAdvance(Object(Amp\CoroutineState))
#4 /.../megan/vendor/amphp/aerys/lib/Server.php(157): Amp\resolve(Object(Generator))
#5 /.../megan/vendor/amphp/aerys/lib/WorkerProcess.php(36): Aerys\Server->start()
#6 /.../megan/vendor/amphp/aerys/lib/Process.php(48): Aerys\WorkerProcess->doStart(Object(Aerys\Console))
#7 /.../megan/vendor/amphp/aerys/bin/aerys-worker(53): Aerys\Process->start(Object(Aerys\Console))
#8 [internal function]: {closure}('000000004a44a61...', NULL)
#9 /.../megan/vendor/amphp/amp/lib/functions.php(791): Generator->current()
#10 /.../megan/vendor/amphp/amp/lib/functions.php(779): Amp\__coroutineAdvance(Object(Amp\CoroutineState))
#11 /.../megan/vendor/amphp/amp/lib/EvReactor.php(133): Amp\resolve(Object(Generator))
#12 /.../megan/vendor/amphp/amp/lib/EvReactor.php(92): Amp\EvReactor->tryImmediate(Object(stdClass))
#13 /.../megan/vendor/amphp/amp/lib/functions.php(46): Amp\EvReactor->run(Object(Closure))
#14 /.../megan/vendor/amphp/aerys/bin/aerys-worker(54): Amp\run(Object(Closure))
#15 {main}
```

My config.php
```php
<?php

// ------------------------------------------------- Environment definition --
define('PRODUCTION_ENV', true);

// ---------------------------------------------------- Global host options --
// @link http://amphp.org/docs/aerys/classes/options.html
const AERYS_OPTIONS = [
    'debug'             => true, // <= HERE is the issue
    'keepAliveTimeout'  => PRODUCTION_ENV ? 20 : 6,
];

// ----------------------------------------------------------- VHost config --
const VHOSTS = [
    1334    => 'localhost',
    1335    => 'localhost',
    1336    => 'localhost',
    1337    => 'localhost',
    1338    => 'localhost',
];

foreach (VHOSTS as $port => $hostname) {
    $host = (new Megan\Host())
        ->name($hostname)
        ->expose('*', $port)
        ->use(new class implements Aerys\Bootable {
            private $server;

            public function boot(Aerys\Server $server, Psr\Log\LoggerInterface $logger)
            {
                $this->server = $server;
            }

            public function __invoke(Aerys\Request $request, Aerys\Response $response)
            {
                $response->setHeader('Content-Type', 'text/plain')
                    ->end(print_r($this->server->monitor(), true));
            }
        });
}

```

And finally my php version
```shell
$ php --version
PHP 7.0.7-5 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

If I remove the 'debug' from AERYS_OPTIONS, everything goes nicely. Awkwardly, -d in command line is also okay.

Tracing the code, there's no difference beetwen -d or 'debug' = true - or anything else, the check method is `array_key_exists`.

In `master`.

**Comment by douggr** [comment]
Despite I would not treat this as "severe" since I can just remove the `debug` option, it's still a bug - I think.

**Comment by bwoebi** [comment]
The difference is that in debug mode we do not set SO_REUSEPORT. Thus, if you try to run it in non-debug mode it tries to establish a connection as many times as you have logical cores. … but without SO_REUSEPORT, the connection can only be established once.

I've just forbidden it via an normal exception explicitly there.

**Comment by kelunik** [comment]
@douggr Just because I'm curious: Why do you create multiple hosts with the same config but different ports?

**Comment by douggr** [comment]
@kelunik I have a NGINX balancer but I can't use multiple hostnames (aerys[1-4].domain.tld for instance) .

```
upstream aerys_nodes {
    ip_hash;

    server localhost:1334 weight=5;
    server localhost:1335;
    server localhost:1336;
    server localhost:13347;
}

server {
    server_name domain.tld;
    location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_pass http://aerys_nodes;
    }

    location /assets {
      ; more config...
    }
}```

Is there a better approach to achieve this? Should I use individual config files?

It's working pretty well though.

**Comment by douggr** [comment]
@bwoebi many thanks!

**Comment by kelunik** [comment]
I expected something like that. You don't need multiple nodes. Just use a single one. Aerys will spawn a worker for each CPU core automatically, adding multiple hosts on different ports doesn't add anything.

**Comment by douggr** [comment]
@kelunik got it. Thank you for clarifying.
